# Generated by Django 5.0.14 on 2026-03-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('MEDIA', 'Media'), ('STORAGE', 'Storage'), ('GAMING', 'Gaming'), ('MONITORING', 'Monitoring'), ('MANAGEMENT', 'Management')], default='MEDIA', max_length=50)),
                ('url', models.URLField(help_text='URL para abrir o serviço (ex: IP do seu PC Gamer)')),
                ('icon', models.CharField(default='Activity', help_text='Nome do ícone Lucide', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
