# Generated by Django 5.0.14 on 2026-03-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('protocol', models.CharField(default='Moonlight / NVIDIA GameStream', max_length=50)),
                ('is_gaming_pc', models.BooleanField(default=False)),
            ],
        ),
    ]
