# Generated by Django 5.0.14 on 2026-03-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remotemachine'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotemachine',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remotemachine',
            name='protocol',
            field=models.CharField(default='RDP', max_length=50),
        ),
    ]
