# Generated by Django 5.0.14 on 2026-03-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remotemachine_url_alter_remotemachine_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotemachine',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
