# Generated by Django 5.0.14 on 2026-03-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_remotemachine_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('MEDIA', 'Media'), ('STORAGE', 'Storage'), ('GAMING', 'Gaming'), ('MONITORING', 'Monitoring'), ('MANAGEMENT', 'Management'), ('CODE', 'Code')], default='MEDIA', max_length=50),
        ),
    ]
